python r_main.py --lambdaa 1e-3
python r_main.py --lambdaa 5e-3
python r_main.py --lambdaa 1e-2
python r_main.py --lambdaa 5e-2
python r_main.py --lambdaa 1e-1
python r_main.py --lambdaa 5e-1
python r_main.py --lambdaa 1e-0
python r_main.py --lambdaa 5e-0
python r_main.py --lambdaa 1e1